### ISSUE TITLE
Unknow read length of r2:216

### ISSUE THREAD

**Issue by jarojasva** [BGI-Qingdao/stLFR_barcode_split#6]
./split_barcode.sh R1_001.fastq.gz R2_001.fastq.gz
Step 1: Loading barcodes ...
Barcode_types: 1536 X 1536 X 1536 = 3623878656
Step 1 : Done
Step 2 : Check r2 length and barcode stype ...
Unknow read length of r2:216.
Please check the R2_001.fastq.gz file!

**Comment by cchd0001** [comment]
Your input read is either not stLFR raw reads or some new version of stLFR reads,  please contact your data customer service person for more details.
